### Get a list of all tournaments
GET {{url}}:{{port}}/api/tournaments/

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
    client.test("Response is array", function () {
        client.assert(Array.isArray(response.body));
    });
%}

### Get all tournaments with a specific name
GET {{url}}:{{port}}/api/tournaments/Elfmeterturnier

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
    client.test("Response is array", function () {
        client.assert(Array.isArray(response.body));
    });
    client.test("All tournaments have correct name", function () {
        response.body.forEach(t => client.assert(t.name.includes("Elfmeterturnier")));
    });
%}

### Create a new tournament
POST {{url}}:{{port}}/api/tournaments/
Content-Type: application/json

{
  "name": "EURO 2024",
  "startDate": "2025-07-01T10:00:00+00:00",
  "endDate": "2025-07-10T18:00:00+00:00"
}

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });

    client.test("Check tournament name", function () {
        client.assert(response.body.name === "EURO 2024");
    });

    client.test("Check tournament has id", function () {
        client.assert(response.body.id !== null);
    });
%}

### Update existing tournament
PUT {{url}}:{{port}}/api/tournaments/
Content-Type: application/json

{
  "id": 3,
  "name": "Champions Cup - Final"
}

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
%}

### Delete existing tournament
DELETE {{url}}:{{port}}/api/tournaments/delete/1

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
%}
