### Get a list of all tournaments
GET {{url}}:{{port}}/api/tournaments/

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
    client.test("Response is array", function () {
        client.assert(Array.isArray(response.body));
    });
%}

### Get all tournaments with a specific name
GET {{url}}:{{port}}/api/tournaments?name=Elfmeterturnier

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
    client.test("Response is array", function () {
        client.assert(Array.isArray(response.body));
    });
    client.test("All tournaments have correct name", function () {
        response.body.forEach(t => client.assert(t.name.includes("Elfmeterturnier")));
    });
%}

### Create a new tournament
POST {{url}}:{{port}}/api/tournaments/
Content-Type: application/json

{
  "name": "EURO 2024",
  "startDate": "2025-07-01T10:00:00Z",
  "endDate": "2025-07-10T18:00:00Z",
  "location": {
    "city": "Berlin",
    "venue": "Olympiastadion"
  },
  "winner": {
    "name": "Team A",
    "coach": "Coach X"
  }
}

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });

    client.test("Check tournament name", function () {
        client.assert(response.body.name === "EURO 2024");
    });

    client.test("Check location", function () {
        client.assert(response.body.location.city === "Berlin");
        client.assert(response.body.location.venue === "Olympiastadion");
    });

    client.test("Check winner", function () {
        client.assert(response.body.winner.name === "Team A");
        client.assert(response.body.winner.coach === "Coach X");
    });
%}

### Update existing tournament
PUT {{url}}:{{port}}/api/tournaments/
Content-Type: application/json

{
  "id": 1,
  "name": "Champions Cup - Final",
  "startDate": "2025-07-01T10:00:00Z",
  "endDate": "2025-07-12T20:00:00Z",
  "location": {
    "city": "Berlin",
    "venue": "Olympiastadion"
  },
  "winner": {
    "name": "Team B",
    "coach": "Coach Y"
  }
}

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
%}

### Delete existing tournament
DELETE {{url}}:{{port}}/api/tournaments/delete/1

> {%
    client.test("Status code is 200", function () {
        client.assert(response.status === 200);
    });
%}
