spring.application.name=tournament-backend
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/tournament-planner
spring.datasource.username=root
spring.datasource.password=root
